### ISSUE TITLE
Canlı yayın ajandası (21Aralık)

### ISSUE THREAD

**Issue by SelmanKahya** [Kommunity-app/kommunity-frontend#162]
Giriş:
- [ ] Sohbet (hayat yazılım)

Kodlama:
- [ ] Chat uygulaması kodlama
- [ ] Mail listesine kayıt (UI + Mailchimp API)
- [ ] Error handling

Chat uygulaması için kullanılacak teknolojiler:
- HTML, CSS, JS 
- Websockets 
- Firebase? Pubnub? Graphql subscriptions + postgre?

Mimari:
![image](https://user-images.githubusercontent.com/3432700/50377254-b899cd80-05ce-11e9-9c95-d9cd899c5735.png)

8. saat sonrasi yapilmasi planlananlar:
- chat ui
- text input asagida kalsin
- yazilar aksin - overflow: scroll
- mesaj duzenleme
- mesaj silme
- kanal degistirme
- veritabani baglantisi
- tag users
- renkli avatar, bas harfler
- load more
- reply ozelligi
- mesaj alintilama
- draft yazi editoru
- `@here` `@channel`
- moderator - kick/ban

**Comment by mustaphaturhan** [comment]
Görüşürüz 😸

**Comment by GokerAkce** [comment]
Şimdiden iyi yayınlar.

**Comment by Ssalih60** [comment]
iyi yayınlar abicim :)

**Comment by KUSEM** [comment]
Tebrikler.

**Comment by semruk** [comment]
adam king

**Comment by BugraEskici** [comment]
Abi mesaj yollarken requestte sender ve text parametresini boş bırakabiliyoruz. Yani isim de boş oluyor mesajda. Rate limit de yok şuan. Bomboş bi ekran oluyor :D
 
```
POST /gql HTTP/1.1
Host: staging-api.kommunity.app

{"operationName":"sendMessage","variables":{"channelUUID":"23ea1110-d6a1-11e8-9f8b-f2801f1b9fd1","sender":" ","text":" "},"query":"mutation sendMessage($channelUUID: String, $sender: String, $text: String) {\n  sendMessage(channelUUID: $channelUUID, sender: $sender, text: $text) {\n    uuid\n    sender\n    text\n    ts\n    __typename\n  }\n}\n"}
```
