### ISSUE TITLE
[frontend] [ui-comp] img

### ISSUE THREAD

**Issue by SelmanKahya** [Kommunity-app/kommunity-frontend#26]
this component will be used to render any image in our app.

expected props:
src=string
lazy= {true | false}

based on lazy flag, it will lazy load the image.

consider:
https://github.com/jasonslyvia/react-lazyload

**Comment by SelmanKahya** [comment]
default lazy = true

**Comment by yasintazeoglu** [comment]
@SelmanKahya  https://reactjs.org/docs/code-splitting.html#reactlazy

**Comment by SelmanKahya** [comment]
that is about bundling, here we need to lazy load the image src

**Comment by SelmanKahya** [comment]
lazy load derken browser'da viewport, yani ekranda gorununce resim yuklensin, bir kutuphane:
https://github.com/loktar00/react-lazy-load
