### ISSUE TITLE
UI Components Folder Structure

### ISSUE THREAD

**Issue by trkaplan** [Kommunity-app/kommunity-frontend#53]
For components organisation I propose,
- Putting components in a folder with the same name. 
- Including an index.js which exports to the component. This way components will be imported like,
`import Button from "@/components/Button"` not like `import Button from "@/components/Button/Button"`*
- Putting styles in a seperate file (this can be optional if the styling is just a few lines)
- Namin conversation; component folder and file names should be ~~camel case~~ **PascalCase**. 
Before;
  **UI/component.js** 
 After; 
  **UI/Component/Component.js** 
  **UI/Component/index.js** 
  **UI/Component/styled.js** 

* Why using a seperate file instead of just putting codes in the index.js file?
Because while editing the file in an editor or working with the file on git/github that would be better to see the actual file name instead of seeing index.js

Related sources:
[Answer, "Styled-components organization" ](https://stackoverflow.com/questions/42987939/styled-components-organization/42996969#42996969)
[Answer, "How to structure Projects using styled components?"](https://spectrum.chat/thread/58e8a3d3-0262-42fd-af30-65d1bfb05bf9?m=MTUzNTExMDk4NjAzNw==)

**Comment by SelmanKahya** [comment]
- File naming
I find it easier to read snake-case formatted file names, for example:
```
longAndComplicatedReactComponent.js
longButLessComplicatedReactComponent.js
```
vs
```
long-and-complicated-react-component.js
```

any reasons why we should use camelCase? historically, there is a tendency to use lower-case file names because of case sensitivity issues in different systems, see `Use Lower Case File Names
` section here https://www.w3schools.com/js/js_conventions.asp.

**Comment by trkaplan** [comment]
> ### File naming
> I find it easier to read snake-case formatted file names, for example:
> 
> ```
> longAndComplicatedReactComponent.js
> longButLessComplicatedReactComponent.js
> ```
> vs
> 
> ```
> long-and-complicated-react-component.js
> ```
> you spend less time trying to parse the string and understand what it does.

in readability case, I agree snake-case (kebap-case) you mentioned is better than PascalCase

> 
> any reasons why we should use camelCase? historically, there is a tendency to use lower-case file names because of case sensitivity issues in different systems, see `Use Lower Case File Names ` section here https://www.w3schools.com/js/js_conventions.asp.

Sorry, I confused words, not camelCase, I meant PascalCase. 
As explained [here](https://www.quora.com/Why-do-React-components-use-PascalCase-for-filenames), react components are classes and named in PascalCase.
Case sensitivity issues on different systems in no more a problem I believe.

> 
> Edit:
> If you are concerned that react components will be harder to differentiate because of other files in the folder, we can use `.jsx` extension.

**Comment by SelmanKahya** [comment]
Yeah, I agree with you on your last point that many of these decisions are based on developer preferences. Assuming that I will always be contributing to this project throughout its life-cycle, and that other developers working on the codebase may want to stop contributing at any point of time, I would prefer designing it in a way that I can maintain easily in the long run :) Hope for the best, prepare for the worst :)

**Comment by SelmanKahya** [comment]
Here is how I think about styling react components:

After defining the design language for the ui components, and implementing them, I think that none of the developers should feel the need to write any css. Even after couple of days of implementation in this repo, you will see that the way our components are styled differs from developer to developer. For example, some prefer using floats to position, some prefer flexbox. It is hard to enforce no one follows bad practices, such as using negative px values to place elements in their place. 

When I do a code review, I would prefer not having to worry about css rules, and whether they will responsive enough to support our cases etc. Spending more time on the business logic, implementing new features is what we aim for. 

We can achieve that by forcing EVERYONE to use predefined set of classnames. NO CUSTOM CSS. Here is an example of how it will look:

```
<div class="rounded shadow-large">
  <img class="width-100" src="...png">
  <div class="pt-2">
    <span class="font-bold text-xlarge">Hello world!</span>
...
```

- defining a rounded box that has a shadow
- there is an image that takes the whole width
- right under, there is a box with padding top, 2 units (we can define `1 unit` to be `0.5rem` etc..)
- inside that box, there is a bolded large text

As you can see, it is REALLY hard to get this wrong. You are not writing any css, no one needs to come up with random padding values, and no need to calculate the spaces/font-sizes while using rem. You don't need to worry about how shadow should look like.

I foresee that 90% of our components should be dummy components, meaning that they will simply render props. No need to clutter the file with css rules defined in js, just html elements with classnames.

I propose that we get rid of all styling rules from react components, and start using predefined set of css classnames that are generated from a configuration file.

**Comment by SelmanKahya** [comment]
@trkaplan any thoughts?

**Comment by trkaplan** [comment]
It looks like a good idea to end these kind of problems you mentioned.

I tried to find production use of this and found this: [5 Takeaways From Using Tailwind CSS In Real Projects](https://medium.com/@nickjbasile/5-takeaways-from-using-tailwind-css-in-real-projects-5fa41393414)

I find it harder to read a long line of class list compared to a syntax colored and ordered list of css rules in a style definition. 
I can use the emmet autocomplete feature of my editor by typing like **ml** for a **margin-left**.
I saw there is an autocomplete extension for my editor. 

I couldn't make it work inside a styled-component.
I followed the instructions here,  [babel-plugin-tailwind-components installation](https://github.com/bradlc/babel-plugin-tailwind-components#readme)

That would be good to hear opinions from @okandungel as a designer. We may have some difficulties to get the exact same design provided by him.

**Comment by SelmanKahya** [comment]
we can discuss this in detail, but what I am doing right now is to add css classes looking at his designs. so we will end up having only things that he used.

**Comment by SelmanKahya** [comment]
resolving this issue.

**Comment by trkaplan** [comment]
> I tried to find production use of this and found this: [5 Takeaways From Using Tailwind CSS In Real Projects](https://medium.com/@nickjbasile/5-takeaways-from-using-tailwind-css-in-real-projects-5fa41393414)

Response from the author to my questions on team's acceptance, responsive design and autocomplete: https://medium.com/@nickjbasile/thanks-for-the-questions-tuncay-acfbf308fb4c

**Comment by SelmanKahya** [comment]
nice 👍
