### ISSUE TITLE
[frontend] signup flow

### ISSUE THREAD

**Issue by SelmanKahya** [Kommunity-app/kommunity-frontend#56]
- validate input (valid email, password not empty, repeating password matches the first field)
- captcha (so we can block spammers)
- handle response and display a nice error to the user

**Comment by bariscc** [comment]
@SelmanKahya 

Would html5 email validation suffice or should we use a pattern for strict validation?
And for the password, should we force the user to use a strong pattern like at least 1 capital letter and number etc. or just limit min-max length?

What are your thoughts? Validation is a pretty opiniated topic.

**Comment by SelmanKahya** [comment]
@bariscc i think this is handled, right? closing it, feel free to reopen
