### ISSUE TITLE
[frontend] ui - input w/ icon

### ISSUE THREAD

**Issue by SelmanKahya** [Kommunity-app/kommunity-frontend#66]
implement text input field with icon as a react component, specs:
https://app.goabstract.com/projects/030f19d0-cadb-11e8-82bb-7102f7c1c598/branches/master/commits/c09f19dbf825dbc3a698dc930088324b29eed4bf/files/BA08F5B2-21D4-4D6A-B130-A1BACAB99B92/layers/5A88E0BA-BD2A-497E-8B67-D7295DFA8920

talk to Okan if you don't have access.

![image](https://user-images.githubusercontent.com/3432700/47973018-8819c680-e056-11e8-9830-6749b0c51580.png)

**Comment by trkaplan** [comment]
Icons passed as a prop with a predefined color. It can't be changed onFocus of the input at the moment.
This can ben implemented, but I have a question @okandungel ,
Will Icon color be always same as focus text color on focus? Or will this be opinionated for some cases we want to fix the color regardless of the focus state? (For example green check icon will still be green when input focused?)
