### ISSUE TITLE
[frontend] ui - switch

### ISSUE THREAD

**Issue by SelmanKahya** [Kommunity-app/kommunity-frontend#70]
implement switch as a react component, specs:
https://app.goabstract.com/projects/030f19d0-cadb-11e8-82bb-7102f7c1c598/branches/master/commits/96a956845a82b9d269035f44f4beb864b0f4b770/files/BA08F5B2-21D4-4D6A-B130-A1BACAB99B92/layers/4103A321-0B9D-42FB-A193-5FDF7291B292

talk to Okan if you don't have access.

![image](https://user-images.githubusercontent.com/3432700/47973104-3c1b5180-e057-11e8-9b1b-94d9ef511237.png)

**Comment by gokhanap** [comment]
https://github.com/TowelSoftware/tailwindcss-toggle

**Comment by SelmanKahya** [comment]
ah nice, lets try to reuse that, good find!
